### PR TITLE
TSDK-807 No longer hardcode User's PK

### PR DESCRIPTION
**Pull request by DiademShoukralla**
## Purpose

Goes with https://github.com/Topl/demo-btc-wallet/pull/10

Users can supply their bitcoin PK instead of it being hardcoded

## Approach

- Added text field for user to suply their PK. This is sent to the server instead of the hardcoded value
- Added a readonly display of their escrow script. This will be used if the user reclaims their BTC back

## Testing

(locally) Ensured I was able to reclaim the users BTC. This proves that the user's PK was sent and encoded correctly in the escrow address&script when the session was initialized. 

## Tickets
* TSDK-807

### CODE REVIEW

**Comment by DiademShoukralla** [comment]
@mundacho  One item that I was not sure if I should include in this PR is if we want to remove the topl-btc-cli module (since it looks like it's functionality is no longer used and it can now be achieved via https://github.com/Topl/demo-btc-wallet/pull/10).

**Review by mundacho — APPROVED** [review]
LGTM!

**Comment by mundacho** [comment]
I think you can remove that. That will be added by the new flutter app.

> @mundacho One item that I was not sure if I should include in this PR is if we want to remove the topl-btc-cli module (since it looks like it's functionality is no longer used and it can now be achieved via [Topl/demo-btc-wallet#10](https://github.com/Topl/demo-btc-wallet/pull/10)).

**Comment by DiademShoukralla** [comment]
I will leave it in in-case they want more code to reference while developing the flutter app

**Pull request merged**
